/********************************************************************
* kinematicsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error kinematicsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablekinematicsDict();
extern void G__cpp_setup_inheritancekinematicsDict();
extern void G__cpp_setup_typetablekinematicsDict();
extern void G__cpp_setup_memvarkinematicsDict();
extern void G__cpp_setup_globalkinematicsDict();
extern void G__cpp_setup_memfunckinematicsDict();
extern void G__cpp_setup_funckinematicsDict();
extern void G__set_cpp_environmentkinematicsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "kinematics.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__kinematicsDictLN_TClass;
extern G__linked_taginfo G__kinematicsDictLN_TBuffer;
extern G__linked_taginfo G__kinematicsDictLN_TMemberInspector;
extern G__linked_taginfo G__kinematicsDictLN_TObject;
extern G__linked_taginfo G__kinematicsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__kinematicsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__kinematicsDictLN_TClonesArray;
extern G__linked_taginfo G__kinematicsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__kinematicsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__kinematicsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__kinematicsDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__kinematicsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__kinematicsDictLN__event_filterBit_;
extern G__linked_taginfo G__kinematicsDictLN__gen_eventInfo_;
extern G__linked_taginfo G__kinematicsDictLN__mc_process_;
extern G__linked_taginfo G__kinematicsDictLN__gen_ttbar_;
extern G__linked_taginfo G__kinematicsDictLN__gen_DrellYan_;
extern G__linked_taginfo G__kinematicsDictLN__genwz_;
extern G__linked_taginfo G__kinematicsDictLN__vec4_;
extern G__linked_taginfo G__kinematicsDictLN__met_;
extern G__linked_taginfo G__kinematicsDictLN__track_;
extern G__linked_taginfo G__kinematicsDictLN__trg_bits_;
extern G__linked_taginfo G__kinematicsDictLN__hlt_info_;
extern G__linked_taginfo G__kinematicsDictLN__mets_;
extern G__linked_taginfo G__kinematicsDictLN__dileadingjets_;
extern G__linked_taginfo G__kinematicsDictLN__run_info_;
extern G__linked_taginfo G__kinematicsDictLN__vertex_;
extern G__linked_taginfo G__kinematicsDictLN__l1_obj_;
extern G__linked_taginfo G__kinematicsDictLN__supercluster_;
extern G__linked_taginfo G__kinematicsDictLN__photon_;
extern G__linked_taginfo G__kinematicsDictLN__electron_;
extern G__linked_taginfo G__kinematicsDictLN__beam_spot_;
extern G__linked_taginfo G__kinematicsDictLN__muon_;
extern G__linked_taginfo G__kinematicsDictLN__gen_jet_;
extern G__linked_taginfo G__kinematicsDictLN__jet_;
extern G__linked_taginfo G__kinematicsDictLN__di_jet_;
extern G__linked_taginfo G__kinematicsDictLN__W_;
extern G__linked_taginfo G__kinematicsDictLN__di_lepton_;
extern G__linked_taginfo G__kinematicsDictLN__tri_lepton_;
extern G__linked_taginfo G__kinematicsDictLN__quar_lepton_;
extern G__linked_taginfo G__kinematicsDictLN__lepton_photon_;
extern G__linked_taginfo G__kinematicsDictLN__dilepton_photon_;
extern G__linked_taginfo G__kinematicsDictLN__event_;

/* STUB derived class for protected member access */
